#pragma once
namespace JASSCPP
{
	union DWFP
	{
		unsigned int dw;
		float fl;
	};
	//float;
	//float &;
	//int;
	//BOOL;
	//void;
	//DWFP;
	typedef int CJassStringSID;
	typedef int HLIGHTNING;
	typedef int HEFFECT;
	typedef int HWEATHEREFFECT;
	typedef int HBOOLEXPR;
	typedef int HLOCATION;
	typedef int HCONDITIONFUNC;
	typedef int HAIDIFFICULTY;
	typedef int HALLIANCETYPE;
	typedef int HATTACKTYPE;
	typedef int HBLENDMODE;
	typedef int HCAMERAFIELD;
	typedef int HDAMAGETYPE;
	typedef int HDIALOGEVENT;
	typedef int HEFFECTTYPE;
	typedef int HFGAMESTATE;
	typedef int HFOGSTATE;
	typedef int HGAMEDIFFICULTY;
	typedef int HGAMEEVENT;
	typedef int HGAMESPEED;
	typedef int HGAMETYPE;
	typedef int HIGAMESTATE;
	typedef int HITEMTYPE;
	typedef int HLIMITOP;
	typedef int HMAPCONTROL;
	typedef int HMAPDENSITY;
	typedef int HMAPFLAG;
	typedef int HMAPSETTING;
	typedef int HMAPVISIBILITY;
	typedef int HPATHINGTYPE;
	typedef int HPLACEMENT;
	typedef int HPLAYERCOLOR;
	typedef int HPLAYEREVENT;
	typedef int HPLAYERGAMERESULT;
	typedef int HPLAYERSCORE;
	typedef int HPLAYERSLOTSTATE;
	typedef int HPLAYERSTATE;
	typedef int HPLAYERUNITEVENT;
	typedef int HRACE;
	typedef int HRACEPREFERENCE;
	typedef int HRARITYCONTROL;
	typedef int HSOUNDTYPE;
	typedef int HSTARTLOCPRIO;
	typedef int HTEXMAPFLAGS;
	typedef int HUNITEVENT;
	typedef int HUNITSTATE;
	typedef int HUNITTYPE;
	typedef int HVERSION;
	typedef int HVOLUMEGROUP;
	typedef int HWEAPONTYPE;
	typedef int HWIDGETEVENT;
	typedef int HUNIT;
	typedef int HCAMERASETUP;
	typedef int HDESTRUCTABLE;
	typedef int HDEFEATCONDITION;
	typedef int HFOGMODIFIER;
	typedef int HFORCE;
	typedef int HGROUP;
	typedef int HIMAGE;
	typedef int HITEM;
	typedef int HITEMPOOL;
	typedef int HLEADERBOARD;
	typedef int HSOUND;
	typedef int HMULTIBOARD;
	typedef int HQUEST;
	typedef int HREGION;
	typedef int HTEXTTAG;
	typedef int HTIMER;
	typedef int HTIMERDIALOG;
	typedef int HTRACKABLE;
	typedef int HTRIGGER;
	typedef int HUBERSPLAT;
	typedef int HUNITPOOL;
	typedef int HBUTTON;
	typedef int HDIALOG;
	typedef int HFILTERFUNC;
	typedef int HPLAYER;
	typedef int HGAMESTATE;
	typedef int HWIDGET;
	typedef int HABILITY;
	typedef int HEVENTID;
	typedef int HRECT;
	typedef int HGAMECACHE;
	typedef int HHASHTABLE;
	typedef int HMULTIBOARDITEM;
	typedef int HQUESTITEM;
	typedef int HTRIGGERACTION;
	typedef int HTRIGGERCONDITION;
	typedef int HEVENT;
	typedef int HTERRAINDEFORMATION;
	typedef int CJassString;
	typedef int CODE;
	typedef int HHANDLE;
	typedef int HAGENT;
};
